import { type Pin } from "@/models/pins";

export const pins: Pin[] = [
  {
    pinId: "pin1",
    reportedBy: "user1",
    title: "MG Marg Trash Bin Overflow",
    description: "Overflowing trash bin near the main square.",
    lat: 27.325,
    lng: 88.611,
    geohash: "tsq6g7",
    city: "Gangtok",
    state: "Sikkim",
    status: "REPORTED",
    severity: "MEDIUM",
    photoUrls: [],
    upvotes: 5,
    createdAt: "2026-04-10T09:00:00Z",
    cleanedAt: null,
  },
  {
    pinId: "pin2",
    reportedBy: "user2",
    title: "Roadside Litter near Taxi Stand",
    description: "Plastic bottles and wrappers scattered by the taxi stand.",
    lat: 27.327,
    lng: 88.613,
    geohash: "tsq6g8",
    city: "Gangtok",
    state: "Sikkim",
    status: "VERIFIED",
    severity: "HIGH",
    photoUrls: [],
    upvotes: 8,
    createdAt: "2026-04-09T14:30:00Z",
    cleanedAt: null,
  },
  {
    pinId: "pin3",
    reportedBy: "user3",
    title: "Park Entrance Debris",
    description: "Construction debris at the park entrance.",
    lat: 27.323,
    lng: 88.609,
    geohash: "tsq6g6",
    city: "Gangtok",
    state: "Sikkim",
    status: "CLEANUP_SCHEDULED",
    severity: "CRITICAL",
    photoUrls: [],
    upvotes: 12,
    createdAt: "2026-04-08T11:00:00Z",
    cleanedAt: null,
  },
  {
    pinId: "pin4",
    reportedBy: "user4",
    title: "Temple Steps Waste",
    description: "Offerings and plastic waste on temple steps.",
    lat: 27.326,
    lng: 88.61,
    geohash: "tsq6g7",
    city: "Gangtok",
    state: "Sikkim",
    status: "REPORTED",
    severity: "LOW",
    photoUrls: [],
    upvotes: 3,
    createdAt: "2026-04-07T16:00:00Z",
    cleanedAt: null,
  },
  {
    pinId: "pin5",
    reportedBy: "user5",
    title: "Bus Stop Garbage",
    description: "Garbage bags left at the main bus stop.",
    lat: 27.324,
    lng: 88.612,
    geohash: "tsq6g7",
    city: "Gangtok",
    state: "Sikkim",
    status: "CLEANED",
    severity: "MEDIUM",
    photoUrls: [],
    upvotes: 10,
    createdAt: "2026-04-06T08:00:00Z",
    cleanedAt: "2026-04-10T10:00:00Z",
  },
];
